# Generated by Django 2.2.28 on 2022-10-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='srd',
        ),
    ]
